# Generated by Django 5.2.4 on 2026-08-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=8, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('intensity', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FilterPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(default='Nenhum filtro relacionado', max_length=100)),
                ('steps', models.IntegerField(default=0, help_text='Passos a partir do fim de curso')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
