# Generated by Django 5.2.4 on 2026-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometricCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_per_pixel', models.FloatField()),
                ('qr_mm', models.FloatField()),
                ('qr_px', models.FloatField()),
                ('qr_content', models.CharField(blank=True, max_length=200)),
                ('deviation', models.FloatField(default=0.0)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
