# Generated by Django 5.2.4 on 2026-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0002_geometriccalibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometriccalibration',
            name='px_per_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='geometriccalibration',
            name='image',
            field=models.ImageField(blank=True, upload_to='geometric/'),
        ),
    ]
