# Generated by Django 5.2.4 on 2026-09-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0003_geometriccalibration_px_per_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectanceCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('means', models.JSONField(default=dict)),
                ('bbox_x', models.PositiveIntegerField(default=0)),
                ('bbox_y', models.PositiveIntegerField(default=0)),
                ('bbox_w', models.PositiveIntegerField(default=0)),
                ('bbox_h', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='reflectance/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
