# Generated by Django 5.2.4 on 2026-09-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0004_reflectancecalibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectanceZeroCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='reflectance/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
