# Generated by Django 5.2.4 on 2026-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0005_reflectancezerocalibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('means', models.JSONField(default=dict)),
                ('reflectance', models.JSONField(blank=True, default=dict)),
                ('folder', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
