# Generated by Django 5.2.4 on 2026-09-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0006_dataacquisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataacquisition',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
