# Generated by Django 5.2.4 on 2026-09-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0007_dataacquisition_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('model_seg', models.FileField(blank=True, upload_to='models/')),
                ('model_det', models.FileField(blank=True, upload_to='models/')),
                ('model_cls', models.FileField(blank=True, upload_to='models/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes', models.JSONField(default=list)),
                ('labels', models.JSONField(default=list)),
                ('polygons', models.JSONField(default=list)),
                ('poly_labels', models.JSONField(default=list)),
                ('points', models.JSONField(default=list)),
                ('point_labels', models.JSONField(default=list)),
                ('image_label', models.CharField(blank=True, max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acquisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='spectral_app.dataacquisition')),
            ],
        ),
        migrations.AddField(
            model_name='dataacquisition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisitions', to='spectral_app.project'),
        ),
    ]
