# Generated by Django 5.2.4 on 2026-09-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0008_project_annotation_dataacquisition_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometriccalibration',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geometric_calibrations', to='spectral_app.project'),
        ),
        migrations.AddField(
            model_name='reflectancecalibration',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflectance_calibrations', to='spectral_app.project'),
        ),
        migrations.AddField(
            model_name='reflectancezerocalibration',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflectance_zero_calibrations', to='spectral_app.project'),
        ),
    ]
