# Generated by Django 5.2.4 on 2026-09-07 22:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_default_project(apps, schema_editor):
    """FilterPosition/BandParameter eram globais ate aqui (1 unico conjunto
    de 6 filtros + 8 bandas pra todo mundo). Agora que sao por projeto,
    marca um projeto como 'padrao' (is_default) e joga essas linhas
    existentes -- com os valores reais que ja estavam calibrados -- pra
    dentro dele, em vez de deixar orfas."""
    Project = apps.get_model('spectral_app', 'Project')
    FilterPosition = apps.get_model('spectral_app', 'FilterPosition')
    BandParameter = apps.get_model('spectral_app', 'BandParameter')

    if Project.objects.filter(is_default=True).exists():
        return  # ja rodou (ou o post_migrate signal ja criou um) -- nao duplica

    default = Project.objects.filter(name='Projeto inicial').first()
    if default is None:
        default = Project.objects.order_by('id').first()
    if default is None:
        default = Project.objects.create(name='Projeto inicial')
    default.is_default = True
    default.save(update_fields=['is_default'])

    FilterPosition.objects.filter(project__isnull=True).update(project=default)
    BandParameter.objects.filter(project__isnull=True).update(project=default)


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0009_geometriccalibration_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandparameter',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band_parameters', to='spectral_app.project'),
        ),
        migrations.AddField(
            model_name='filterposition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_positions', to='spectral_app.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bandparameter',
            name='nm',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='filterposition',
            name='index',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='bandparameter',
            unique_together={('project', 'nm')},
        ),
        migrations.AlterUniqueTogether(
            name='filterposition',
            unique_together={('project', 'index')},
        ),
        migrations.RunPython(backfill_default_project, migrations.RunPython.noop),
    ]
