# Generated by Django 5.2.4 on 2026-09-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0010_bandparameter_project_filterposition_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.IntegerField(default=0)),
                ('contrast', models.IntegerField(default=32)),
                ('saturation', models.IntegerField(default=64)),
                ('hue', models.IntegerField(default=0)),
                ('gamma', models.IntegerField(default=100)),
                ('gain', models.IntegerField(default=0)),
                ('sharpness', models.IntegerField(default=3)),
                ('backlight_compensation', models.IntegerField(default=1)),
                ('power_line_frequency', models.IntegerField(default=2)),
                ('white_balance_automatic', models.BooleanField(default=True)),
                ('white_balance_temperature', models.IntegerField(default=4600)),
                ('auto_exposure', models.BooleanField(default=True)),
                ('exposure_time_absolute', models.IntegerField(default=157)),
                ('exposure_dynamic_framerate', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='camera_settings', to='spectral_app.project')),
            ],
        ),
    ]
