# Generated by Django 5.2.4 on 2026-09-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0011_camerasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometriccalibration',
            name='image',
            field=models.ImageField(blank=True, upload_to='geometric_parametrization/'),
        ),
        migrations.AlterField(
            model_name='reflectancecalibration',
            name='image',
            field=models.ImageField(blank=True, upload_to='reflectance_parametrization/'),
        ),
        migrations.AlterField(
            model_name='reflectancezerocalibration',
            name='image',
            field=models.ImageField(blank=True, upload_to='reflectance_parametrization/'),
        ),
    ]
