# Generated by Django 5.2.4 on 2026-09-10 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0012_alter_geometriccalibration_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataacquisition',
            name='means',
        ),
        migrations.RemoveField(
            model_name='dataacquisition',
            name='reflectance',
        ),
        migrations.CreateModel(
            name='ROIMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('box', 'Retângulo'), ('polygon', 'Polígono'), ('point', 'Ponto'), ('otsu', 'Otsu (automático)'), ('yolo_det', 'YOLO detecção (automático)'), ('yolo_seg', 'YOLO segmentação (automático)')], max_length=20)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('contour', models.JSONField(blank=True, default=dict)),
                ('means', models.JSONField(default=dict)),
                ('reflectance', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_measurements', to='spectral_app.dataacquisition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_measurements', to='spectral_app.project')),
            ],
            options={
                'ordering': ['acquisition', 'index'],
                'unique_together': {('acquisition', 'index')},
            },
        ),
    ]
