# Generated by Django 5.2.4 on 2026-09-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0014_alter_geometriccalibration_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roimeasurement',
            options={'ordering': ['acquisition', 'method', 'index']},
        ),
        migrations.AlterUniqueTogether(
            name='roimeasurement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='roimeasurement',
            name='method',
            field=models.CharField(choices=[('box', 'Retângulo'), ('circle', 'Círculo'), ('ellipse', 'Elipse'), ('polygon', 'Polígono'), ('point', 'Ponto'), ('otsu', 'Otsu (automático)'), ('yolo_det', 'YOLO detecção (automático)'), ('yolo_seg', 'YOLO segmentação (automático)')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='roimeasurement',
            unique_together={('acquisition', 'method', 'index')},
        ),
    ]
