# Generated by Django 5.2.4 on 2026-09-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0015_alter_roimeasurement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometriccalibration',
            name='qr_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
