# Generated by Django 5.2.4 on 2026-09-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0016_geometriccalibration_qr_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasettings',
            name='auto_exposure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='white_balance_automatic',
            field=models.BooleanField(default=False),
        ),
    ]
