# Generated by Django 5.2.4 on 2026-09-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0017_alter_camerasettings_auto_exposure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflectancezerocalibration',
            name='mean',
        ),
        migrations.AddField(
            model_name='bandparameter',
            name='exposure_time_absolute',
            field=models.IntegerField(default=157),
        ),
        migrations.AddField(
            model_name='reflectancezerocalibration',
            name='means',
            field=models.JSONField(default=dict),
        ),
    ]
