# Generated by Django 5.2.4 on 2026-09-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0018_remove_reflectancezerocalibration_mean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandparameter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
