# Generated by Django 5.2.4 on 2026-09-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0019_bandparameter_updated_camerasettings_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometriccalibration',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reflectancecalibration',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reflectancezerocalibration',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
