# Generated by Django 5.2.4 on 2026-09-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0020_alter_geometriccalibration_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roimeasurement',
            name='area_mm2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roimeasurement',
            name='area_px',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roimeasurement',
            name='bbox_height_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roimeasurement',
            name='bbox_height_px',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roimeasurement',
            name='bbox_width_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roimeasurement',
            name='bbox_width_px',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
