# Generated by Django 5.2.4 on 2026-09-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0021_roimeasurement_area_mm2_roimeasurement_area_px_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model_cls_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
