# Generated by Django 5.2.4 on 2026-09-27 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0022_project_model_cls_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataacquisition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='spectral_app.project'),
        ),
        migrations.AlterField(
            model_name='geometriccalibration',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometric_calibration', to='spectral_app.project'),
        ),
        migrations.AlterField(
            model_name='reflectancecalibration',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflectance_calibration', to='spectral_app.project'),
        ),
        migrations.AlterField(
            model_name='reflectancezerocalibration',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflectance_zero_calibration', to='spectral_app.project'),
        ),
    ]
