# Generated by Django 5.2.4 on 2026-09-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0023_alter_dataacquisition_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='poly_kinds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='roimeasurement',
            name='method',
            field=models.CharField(choices=[('box', 'Retângulo'), ('ellipse', 'Elipse'), ('polygon', 'Polígono'), ('point', 'Ponto'), ('otsu', 'Otsu (automático)'), ('yolo_det', 'YOLO detecção (automático)'), ('yolo_seg', 'YOLO segmentação (automático)')], max_length=20),
        ),
    ]
