# Generated by Django 5.2.4 on 2026-09-27 14:20
#
# "circle" deixou de existir como SelectionMethod (ver 0024) -- a distincao
# circulo/elipse era so um heuristico por proporcao (largura/altura >= 0.92)
# em cima da mesma classificacao por contagem de pontos que causava o bug de
# poligono desenhado a mao virar "elipse" por coincidencia. Reclassifica
# qualquer ROIMeasurement antigo com method="circle" pra "ellipse", que e o
# rotulo mais proximo que ainda existe.

from django.db import migrations


def relabel_circle_as_ellipse(apps, schema_editor):
    ROIMeasurement = apps.get_model('spectral_app', 'ROIMeasurement')
    ROIMeasurement.objects.filter(method='circle').update(method='ellipse')


def relabel_ellipse_as_circle_noop(apps, schema_editor):
    pass  # nao da pra saber quais eram originalmente circulo -- reverso e um no-op


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0024_annotation_poly_kinds_alter_roimeasurement_method'),
    ]

    operations = [
        migrations.RunPython(relabel_circle_as_ellipse, relabel_ellipse_as_circle_noop),
    ]
