# Generated by Django 5.2.4 on 2026-09-27 14:33
# (editado a mao: separado em 3 migracoes -- adiciona campo, migra dado
# usando poly_kinds ENQUANTO ele ainda existe, so depois remove poly_kinds.
# Fazer tudo numa migracao so, como o makemigrations gerou, apagaria
# poly_kinds ANTES de dar pra usar ele pra separar elipse de poligono.)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0025_relabel_circle_as_ellipse'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ellipse_labels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='annotation',
            name='ellipses',
            field=models.JSONField(default=list),
        ),
    ]
