# Generated by Django 5.2.4 on 2026-10-03 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0031_project_owner_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterizationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_notes', to='spectral_app.project')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
