# Generated by Django 5.2.4 on 2026-10-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_app', '0032_parameterization_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterizationnote',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
